version: '3.6'

services:
  app:
    image: node:16.0-alpine
    command: npm run serve
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app

  cypress:
    image: zerosuxx/cypress-browser-sync:latest
    working_dir: /app
#    environment:
#      DISPLAY:
    volumes:
      - ./.:/app
    ipc: host
    network_mode: host
