version: '3.6'

services:
  app:
    image: php:7.3.28-cli
    command: 'php -S 0.0.0.0:8080 /app/server.php'
    ports:
      - 8080:8080
    volumes:
      - ./.:/app

  cypress:
    image: zerosuxx/cypress-browser-sync:latest
    user: '1000'
    environment:
      DISPLAY:
    volumes:
      - ./.:/app
    working_dir: /app
    ipc: host
    network_mode: host
    depends_on:
      - app
