version: '3.6'

services:
  app:
    image: php:7.3.28-cli
    command: 'php -S 0.0.0.0:8080 /app/server.php'
    ports:
      - 8080:8080
    volumes:
      - ./.:/app

  node:
    image: zerosuxx/node-vuejs:latest
    command: npm run serve
    working_dir: /app
    ports:
      - 8081:8081
    volumes:
      - ./.:/app

  cypress:
    image: zerosuxx/cypress-browser-sync:latest
    working_dir: /app
#    environment:
#      DISPLAY:
    volumes:
      - ./.:/app
    ipc: host
    network_mode: host
