name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build application
        run: make build
      - name: Run tests
        run: make test-ci
      - name: Create cypress recordings artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-recordings
          path: |
            test/e2e/cypress/videos
            test/e2e/cypress/screenshots